import subprocess as sub 
import numpy as np 

# converts and edits the .txt outfiles generated by the ltspice code 
# to a .csv file for further analysis of the data. 
t = np.array( [ 0.1 , 0.2 , 0.3 , 0.5 , 1 , 2 , 5  ])
t =  (10*t).astype( int )  
t = t.astype( str )
s1 = np.full(  len( t ) ,
             "sed 's/[[:blank:]]\{1,\}/,/g' /Users/ashmitbathla/Desktop/SHH-Circuit/data/file")
s2 = np.full(  len( t ) , 
             ".txt >/Users/ashmitbathla/Desktop/SHH-Circuit/data/newfile")
s3 = np.full( len(t),
             ".csv")
filename = np.char.add( s1 , t )
filename = np.char.add( filename , s2 )
filename = np.char.add( filename , t )
filename = np.char.add( filename , s3 )

for name in filename: 
    sub.call( name  , shell = True )